"""Compatibility tests for extended_scorer after registry refactor.

Verifies that score_extended() still works correctly after importing
INDICATOR_REGISTRY from bot.scorer instead of defining its own.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from bot.scorer import INDICATOR_REGISTRY as PROD_REGISTRY, EXTENDED_13, PRODUCTION_10
from bot.research.extended_scorer import score_extended


def _make_df(rows: int = 120, seed: int = 42) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    close = 100.0 + rng.normal(0, 1, rows).cumsum()
    high = close + abs(rng.normal(0, 0.5, rows))
    low = close - abs(rng.normal(0, 0.5, rows))
    return pd.DataFrame({
        "open": close - 0.3,
        "high": high,
        "low": low,
        "close": close,
        "volume": rng.uniform(1000, 5000, rows),
    })


class TestExtendedRegistryCompatibility:
    def test_extended_registry_superset_of_production(self):
        """After refactor, extended_scorer uses production registry directly.
        It must contain all production indicators (original 8 + extras).
        """
        from bot.research.extended_scorer import INDICATOR_REGISTRY as EXT_REGISTRY
        # Every production key must exist in the extended registry
        for key in PROD_REGISTRY:
            assert key in EXT_REGISTRY, f"Production key '{key}' missing from extended registry"

    def test_score_extended_still_works(self):
        """score_extended() must return a valid result dict with mixed weights."""
        weights = {
            "ema_trend": 1.0,
            "macd_signal": 0.0,
            "rsi_position": 1.0,
            "rsi_divergence": 0.0,
            "bb_position": 1.5,
            "volume_spike": 2.0,
            "pressure": 0.0,
            "candle_direction": 0.0,
            "stochrsi": 2.5,
            "hull_ma": 1.0,
        }
        df = _make_df(120)
        result = score_extended(df, weights=weights, btc_trend="Sideways")

        required_keys = {"direction", "confidence", "leverage", "risk_reward", "signals", "go", "btc_trend", "raw_confidence"}
        assert required_keys.issubset(result.keys()), f"Missing keys: {required_keys - result.keys()}"
        assert isinstance(result["confidence"], (int, float))
        assert result["confidence"] >= 0
        assert isinstance(result["go"], bool)

    def test_research_pipeline_weights_work(self):
        """Actual research winner-style weights produce valid results.

        Simulates the kind of specialized weight config generated by the
        research pipeline (high selectivity: 2-3 indicators, others zeroed).
        """
        # Research-generated weight combos (HiddenGem-like, Sniper-like)
        research_weight_sets = [
            # HiddenGem-like: EMA + BB + Vol
            {
                "ema_trend": 1.5, "macd_signal": 0.0, "rsi_position": 0.0,
                "rsi_divergence": 0.0, "bb_position": 1.5, "volume_spike": 2.0,
                "pressure": 0.0, "candle_direction": 0.0,
            },
            # Sniper-like: BB + Vol + Candle
            {
                "ema_trend": 0.0, "macd_signal": 0.0, "rsi_position": 0.0,
                "rsi_divergence": 0.0, "bb_position": 1.5, "volume_spike": 2.0,
                "pressure": 0.0, "candle_direction": 1.0,
            },
            # Research winner with extended indicator
            {
                "ema_trend": 0.0, "macd_signal": 0.0, "rsi_position": 1.0,
                "rsi_divergence": 0.0, "bb_position": 1.5, "volume_spike": 2.0,
                "pressure": 0.0, "candle_direction": 0.0,
                "stochrsi": 2.5,
            },
            # Extended-only: obv_trend + stochrsi + supertrend
            {
                "ema_trend": 0.0, "macd_signal": 0.0, "rsi_position": 0.0,
                "rsi_divergence": 0.0, "bb_position": 0.0, "volume_spike": 1.0,
                "pressure": 0.0, "candle_direction": 0.0,
                "obv_trend": 1.5, "stochrsi": 2.0, "supertrend": 1.5,
            },
        ]

        df = _make_df(120)
        for i, weights in enumerate(research_weight_sets):
            result = score_extended(df, weights=weights, btc_trend="Sideways")
            assert isinstance(result["confidence"], (int, float)), (
                f"Weight set {i}: confidence must be numeric"
            )
            assert result["confidence"] >= 0, f"Weight set {i}: confidence must be >= 0"
            assert isinstance(result["go"], bool), f"Weight set {i}: go must be bool"

    def test_score_extended_insufficient_data_returns_no_signal(self):
        """score_extended() with too few rows returns a no-signal result."""
        weights = {"ema_trend": 1.0, "bb_position": 1.5, "volume_spike": 2.0}
        df = _make_df(30)
        result = score_extended(df, weights=weights)
        assert result["go"] is False
        assert result["direction"] is None

    def test_score_extended_all_extended_13_weights(self):
        """All 13 extended indicators can be used in score_extended() without error."""
        weights = {
            "ema_trend": 0.0, "macd_signal": 0.0, "rsi_position": 0.0,
            "rsi_divergence": 0.0, "bb_position": 0.0, "volume_spike": 1.0,
            "pressure": 0.0, "candle_direction": 0.0,
        }
        for name in EXTENDED_13:
            weights[name] = 1.0

        df = _make_df(120)
        result = score_extended(df, weights=weights)
        assert isinstance(result["confidence"], (int, float))
        # All active extended indicators should appear in signals
        for name in EXTENDED_13:
            assert name in result["signals"], f"{name} should be in signals"
